apps/core/urls.py
from apps.core.views import index, search_results, favorite_control, show_detail
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='inicio'),
    path('search/', search_results, name='search_results'),
    path('favorito/<int:id>', favorite_control, name='favorite_control'),
    path('detalle/<int:id>', show_detail, name='show_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/furnitures/urls.py
""" Entertainments routes. """
from apps.furnitures.views import furniture_add, furnitures_list, edit_furniture, delete_furniture
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'furnitures'

urlpatterns = [
    path('agregar/', furniture_add, name='furniture_add'),
    path('lista/<int:id>/', furnitures_list, name='furnitures_list'),
    path('editar/<int:id>/', edit_furniture, name='edit_furniture'),
    path('eliminar/<int:id>/', delete_furniture, name='delete_furniture'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("users/", include ("django.contrib.auth.urls")),
    path("users/", include("apps.users.urls")),
    path("motores/", include("apps.motor_app.urls")),
    path("electronica/", include("apps.electronics.urls")),
    path("mobiliarios/", include("apps.furnitures.urls")),
    path("entretenimiento/", include("apps.entertainments.urls")),
]

# Configuración para que se muestren las imagenes en el navegador
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/furnitures/models.py
""" Furnitures models. """
from django.db import models
from apps.core.models import BaseClass

# Create your models here.


class FurnitureCategory(models.Model):
    """ Modelo de categorias para mobiliarios. """
    name = models.CharField(max_length=145, null=False)

    class Meta:
        """ Verbos plurares y singurales. """
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return f"{self.name}"


class Furniture(BaseClass):
    """ Modelo para mobiliarios. """
    category = models.ForeignKey(
        FurnitureCategory,
        related_name='furnitures',
        on_delete=models.SET_NULL,
        null=True
        )

apps/furnitures/forms.py
""" Forms Furnitures. """
from django import forms

class FurnitureForm(forms.Form):
    """ Formularios para oferta de mobliliarios. """
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Título',
        max_length=255,
        min_length=1,
        required=True,
    )

    price = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Precio',
        min_value=1,
        required=True,
        error_messages={
            'invalid': 'Por favor, ingrese un número válido para el precio.',
        }
    )

    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Ubicación',
        max_length=255,
        min_length=4,
        required=True,
    )

    phone1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Celular 1',
        min_length=8,
        required=True,
        error_messages={
            'invalid': 'Por favor, ingrese un número de contacto válido',
        }

    )

    phone2 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Celular 2',
        min_length=8,
        required=False
    )

    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Email',
        error_messages={
            'invalid': 'Por favor, ingrese un email válido.',
        }

    )
    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label='Descripción',
        max_length=255,
        min_length=1,
        required=True,
    )

    images = forms.ImageField(
    widget=forms.FileInput(attrs={'class': 'form-control'}),
    label='Imagen',
    required=False,
    )

apps/furnitures/views.py
""" Views Furniture. """
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404, HttpResponseServerError

from apps.core.models import ImageBase
from .models import Furniture, FurnitureCategory
from .forms import FurnitureForm

# Create your views here.


def furniture_add(request):
    """ Vista para electrónicos. """
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = FurnitureForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                images = request.FILES.getlist('images')
                category_id = request.POST.get('category_id')
                print("Categoría seleccionada:", category_id)

                new_furniture = Furniture.objects.create(
                    title=data['title'],
                    category_id=category_id,
                    price=data['price'],
                    location=data['location'],
                    phone_number1=data['phone1'],
                    phone_number2=data['phone2'],
                    email=data['email'],
                    description=data['description'],
                    user=request.user,
                )

                images = request.FILES.getlist('images')
                for image in images:
                    ImageBase.objects.create(image=image, product=new_furniture)

                messages.success(
                    request, 'Oferta de Mobiliario agregado!'
                )

                return redirect(reverse('core:inicio'))

            else:
                print(request.FILES)
                print("Formulario no valido")
                print(form.errors)
                return HttpResponseServerError("Formulario no válido. Por favor, revise los datos.")

        else:
            form = FurnitureForm()

        context = {
            'categories': FurnitureCategory.objects.all(),
            'form': form,
        }

        return render(request, 'furnitures/furniture_form.html', context)

    else:
        messages.error(request, '¡Usuario no autenticado!')
        return redirect(reverse('core:inicio'))


def furnitures_list(request, id):

    category_instane = FurnitureCategory.objects.get(id=id)
    furniture_filter = Furniture.objects.filter(category=category_instane).order_by('-id')

    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(furniture_filter, 5)
        publications = paginator.page(page)
    except:
        raise Http404

    context = {
        'entity': publications,
        'paginator': paginator
    }

    return render(request, 'furnitures/list.html', context)


def edit_furniture(request, id):

    if request.user.is_authenticated:

        my_furniture = Furniture.objects.get(id=id)

        if request.method == 'POST':
            form = FurnitureForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data

                category_id = request.POST.get('category_id')
                category = FurnitureCategory.objects.get(id=category_id)

                my_furniture.title = data['title']
                my_furniture.price = data['price']
                my_furniture.location = data['location']
                my_furniture.phone_number1 = data['phone1']
                my_furniture.phone_number2 = data['phone2']
                my_furniture.email = data['email']
                my_furniture.description = data['description']
                my_furniture.category = category

                my_furniture.save()

                messages.success(request, 'Oferta de Mobiliario editada')
                return redirect(reverse('core:inicio'))

            else:

                print("Formulario no valido")
                print(form.errors)
                return redirect(reverse('core:inicio'))

        else:

            data = {
                'title': my_furniture.title,
                'price': my_furniture.price,
                'location': my_furniture.location,
                'phone1': my_furniture.phone_number1,
                'phone2': my_furniture. phone_number2,
                'email': my_furniture.email,
                'description': my_furniture.description,
            }

            form = FurnitureForm(initial=data)

            return render(request, 'furnitures/edit.html',
                        {'form': form,
                        'my_furniture': my_furniture,
                        'categories': FurnitureCategory.objects.all()}
                        )

    else:
        messages.error(request, '¡Usuario no autenticado!')
        return redirect(reverse('core:inicio'))


def delete_furniture(request, id):

    print(f'Mobiliario con id: "{id}" eliminado')

    to_delete = Furniture.objects.get(id=id)
    to_delete.delete()

    messages.warning(
                request, 'Oferta de Mobiliario eliminado!'
            )

    return redirect(reverse('core:inicio'))

apps/furnitures/templates/furnitures/edit.html
{% extends 'base.html' %}

{% block title %} Editar Oferta Mobiliario {% endblock %}

{% block content %}
<div class="container mt-5 col-6">
    <div class="row">
        <div class="card p-3">
            <h1>Editar Mobiliario</h1>
            <form action="#" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <div class="mb-3">
                            {{ form.title.label_tag }}
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Categoria:</label>
                            <select class="form-select" id="category_id" name="category_id">
                                <option selected>Seleccionar Categoria</option>
                                {% for category in categories %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            {{ form.price.label_tag }}
                            {{ form.price }}
                            {% if form.price.errors %}
                            <div class="text-danger">
                                {{ form.price.errors }}
                            </div>
                            {% endif %}
                        </div>
                        <!-- <div class="mb-3">
                            <label for="images" class="form-label">Imagenes:</label>
                            <input type="file" multiple  class="form-control" id="images" name="images" required>
                        </div> -->
                        <div class="mb-3">
                            {{ form.location.label_tag }}
                            {{ form.location }}
                        </div>
                        <div class="mb-3">
                            {{ form.phone1.label_tag }}
                            {{ form.phone1 }}
                        </div>
                        <div class="mb-3">
                            {{ form.phone2.label_tag }}
                            {{ form.phone2 }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                        <div class="mb-3">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-warning">Editar Oferta</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/furnitures/templates/furnitures/furniture_form.html
{% extends 'base.html' %}

{% block title %} Ofertar Mobiliario {% endblock %}

{% block content %}
<div class="container mt-5 col-6">
    <div class="row">
        <div class="card p-3">
            <h1>Mobiliario</h1>
            <form action="{% url 'furnitures:furniture_add' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <div class="mb-3">
                            {{ form.title.label_tag }}
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Categoria:</label>
                            <select class="form-select" id="category_id" name="category_id">
                                <option selected>Seleccionar Categoria</option>
                                {% for category in categories %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            {{ form.price.label_tag }}
                            {{ form.price }}
                            {% if form.price.errors %}
                            <div class="text-danger">
                                {{ form.price.errors }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            {{ form.images.label_tag }}
                            {{ form.images }}
                        </div>
                        <div id="additional_image_fields">
                            <!-- Input adicional -->
                        </div>
                        <br>
                        <button type="button" id="add_image_field" class="btn btn-secondary">Agregar más imágenes</button>
                        <br>
                        <br>
                        <div class="mb-3">
                            {{ form.location.label_tag }}
                            {{ form.location }}
                        </div>
                        <div class="mb-3">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                            {{ form.phone1.label_tag }}
                            {{ form.phone1 }}
                        </div>
                        <div class="mb-3">
                            {{ form.phone2.label_tag }}
                            {{ form.phone2 }}
                        </div>
                        <div class="mb-3">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Ofertar</button>
            </form>
        </div>
    </div>
</div>

<script>
    document.getElementById("add_image_field").addEventListener("click", function () {
        var newInput = document.createElement("input");
        newInput.type = "file";
        newInput.name = "images";
        newInput.className = "form-control";
        newInput.multiple = true;
        document.getElementById("additional_image_fields").appendChild(newInput);
    });
</script>
{% endblock %}

apps/furnitures/templates/furnitures/list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Lista Mobiliarios {% endblock %}

{% block content %}
{% if entity %}
{% for furniture in entity %}
<div class="row m-2 justify-content-center">
    <div class="col-10 card shadow-sm">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-2">
                    {% if furniture.images.all %}
                        <img src="{{ furniture.images.all.first.image.url }}" alt="{{ furniture.title }}" class="img-fluid float-start">
                    {% endif %}
                </div>
                <div class="card-title col-6 mx-3">
                    <a href="{% url 'core:show_detail' id=furniture.id %}"
                    class="fw-bolder link-underline link-underline-opacity-0">{{furniture.title}}</a>
                    <h5>{{furniture.price|intcomma}}</h5>
                    <footer>
                        Ofrecido por <span>{{furniture.user}}</span>
                        | Ubicación {{furniture.location}}
                    </footer>
                </div>
                <div class="col-3 d-flex justify-content-end align-items-center">
                    {% if user == furniture.user %}
                    <a href="{% url 'furnitures:edit_furniture' id=furniture.id %}" class="btn btn-warning me-1 btn-sm">
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger btn-sm me-1" data-bs-toggle="modal"
                        data-bs-target="#delete{{furniture.id}}">
                        <i class="bi bi-trash-fill"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="delete{{furniture.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">ELIMINAR OFERTA</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    ¿Seguro que quieres elimar la oferta: {{furniture.title}}?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close</button>
                                    <a href="{% url 'furnitures:delete_furniture' id=furniture.id %}"
                                        class="btn btn-danger">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endfor %}
<div>
    {% include 'includes/paginator.html' %}
    </div>
{% else %}
<div class="row mt-5 justify-content-center">
    <div class="col card shadow-sm text-center">
        <h5 class="m-2">Ofertas no encontradas</h5>
    </div>
</div>
{% endif %}
{% endblock %}