apps/core/urls.py
from apps.core.views import index, search_results, favorite_control, show_detail
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='inicio'),
    path('search/', search_results, name='search_results'),
    path('favorito/<int:id>', favorite_control, name='favorite_control'),
    path('detalle/<int:id>', show_detail, name='show_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/motor_app/urls.py
""" Motors routes. """
from apps.motor_app.views import motor_add, motor_app_list, edit_motor_app, delete_motor_app
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'motor_app'

urlpatterns = [
    path('agregar/', motor_add, name='motor_add'),
    path('lista/<int:id>/', motor_app_list, name='motor_app_list'),
    path('editar/<int:id>/', edit_motor_app, name='edit_motor_app'),
    path('eliminar/<int:id>/', delete_motor_app, name='delete_motor_app'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("users/", include ("django.contrib.auth.urls")),
    path("users/", include("apps.users.urls")),
    path("motores/", include("apps.motor_app.urls")),
    path("electronica/", include("apps.electronics.urls")),
    path("mobiliarios/", include("apps.furnitures.urls")),
    path("entretenimiento/", include("apps.entertainments.urls")),
]

# Configuración para que se muestren las imagenes en el navegador
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/motor_app/models.py
""" Motors models. """
from django.db import models
from apps.core.models import BaseClass

# Create your models here.


class MotorCategory(models.Model):
    """ Modelo de categorias para motorizados. """
    name = models.CharField(max_length=145)

    class Meta:
        """ Verbos plurares y singurales. """
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return f"{self.name}"


class Motor(BaseClass):
    """ Modelo para motorizados. """
    brand = models.CharField(max_length=145, null=False)
    model = models.CharField(max_length=145, null=False)
    fuel = models.CharField(max_length=50, null=False)
    transmission = models.CharField(max_length=145, null=False)
    year = models.PositiveBigIntegerField(null=False)
    color = models.CharField(max_length=50, null=False)
    category = models.ForeignKey(
        MotorCategory,
        related_name='motors',
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self) -> str:
        return f"{self.brand} {self.model} {self.year} {self.color} {self.transmission}"

apps/motor_app/forms.py
""" Forms Motors. """
from datetime import date

from django import forms


class MotorForm(forms.Form):
    """ Formularios para oferta de mobliliarios. """
    FUEL_CHOICES = [
        ('Nafta', 'Nafta'),
        ('Diesel', 'Diesel'),
        ('Alcohol', 'Alcohol'),
        ('Flex', 'Flex'),
        ('Eléctrico', 'Eléctrico'),
    ]

    TRANSMISSION_CHOICES = [
        ('manual', 'Manual'),
        ('automatic', 'Automática'),
    ]

    YEAR_CHOICES = [(year, year)
                    for year in range(1886, date.today().year + 1)]

    # Unico de Motor
    brand = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Marca',
        max_length=255,
        min_length=1,
        required=True,
    )
    model = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Modelo',
        max_length=255,
        min_length=1,
        required=True,
    )
    fuel = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Combustible',
        choices=FUEL_CHOICES,
        required=True,
    )
    transmission = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Transmisión',
        choices=TRANSMISSION_CHOICES,
        required=True,
    )
    year = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Año',
        required=True,
        choices=YEAR_CHOICES,
        initial=date.today().year,
    )
    color = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Color',
        max_length=255,
        min_length=4,
        required=True,
    )

    # Compartido con BaseClass
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Título',
        max_length=255,
        min_length=1,
        required=True,
    )

    description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label='Descripción',
        max_length=255,
        min_length=1,
        required=True,
    )

    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Ubicación',
        max_length=255,
        min_length=4,
        required=True,
    )

    price = forms.IntegerField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Precio',
        min_value=1,
        required=True,
        error_messages={
            'invalid': 'Por favor, ingrese un número válido para el precio.',
        }
    )

    phone1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Celular 1',
        min_length=8,
        required=True,
        error_messages={
            'invalid': 'Por favor, ingrese un número de contacto válido',
        }
    )

    phone2 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Celular 2',
        min_length=8,
        required=False
    )

    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Email',
        error_messages={
            'invalid': 'Por favor, ingrese un email válido.',
        }
    )

    images = forms.ImageField(
    widget=forms.FileInput(attrs={'class': 'form-control'}),
    label='Imagen',
    required=False,
    )

apps/motor_app/views.py
""" Views Motors. """
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404, HttpResponseServerError

from apps.core.models import ImageBase
from .models import MotorCategory, Motor
from .forms import MotorForm


# Create your views here.
def motor_add(request):
    """ Vista para motorizados. """
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = MotorForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                images = request.FILES.getlist('images')
                category_id = request.POST.get('category_id')
                print("Categoría seleccionada:", category_id)

                new_motor = Motor.objects.create(
                    title=data['title'],
                    price=data['price'],
                    location=data['location'],
                    brand=data['brand'],
                    model=data['model'],
                    fuel=data['fuel'],
                    transmission=data['transmission'],
                    year=int(data['year']),
                    color=data['color'],
                    category_id=category_id,
                    email=data['email'],
                    phone_number1=data['phone1'],
                    phone_number2=data['phone2'],
                    description=data['description'],
                    user=request.user,
                )

                images = request.FILES.getlist('images')
                for image in images:
                    ImageBase.objects.create(image=image, product=new_motor)

                messages.success(
                    request, 'Oferta de Motor agregado!'
                )

                return redirect(reverse('core:inicio'))

            else:
                print(request.FILES)
                print("Formulario no valido")
                print(form.errors)
                return HttpResponseServerError("Formulario no válido. Por favor, revise los datos.")

        else:
            form = MotorForm()

        context = {
            'categories': MotorCategory.objects.all(),
            'form': form,
        }

        return render(request, 'motor_app/motor_form.html', context)

    else:
        messages.error(request, '¡Usuario no autenticado!')
        return redirect(reverse('core:inicio'))


def motor_app_list(request, id):

    category_instane = MotorCategory.objects.get(id=id)
    motor_filter = Motor.objects.filter(category=category_instane).order_by('-id')

    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(motor_filter, 5)
        publications = paginator.page(page)
    except:
        raise Http404

    context = {
        'entity': publications,
        'paginator': paginator
    }

    return render(request, 'motor_app/list.html', context)


def edit_motor_app(request, id):

    if request.user.is_authenticated:

        my_motor = Motor.objects.get(id=id)

        if request.method == 'POST':
            form = MotorForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data

                category_id = request.POST.get('category_id')
                category = MotorCategory.objects.get(id=category_id)

                #Motor data
                my_motor.brand = data['brand']
                my_motor.model = data['model']
                my_motor.fuel = data['fuel']
                my_motor.transmission = data['transmission']
                my_motor.year = data['year']
                my_motor.color = data['color']

                #Base data
                my_motor.title = data['title']
                my_motor.price = data['price']
                my_motor.location = data['location']
                my_motor.phone_number1 = data['phone1']
                my_motor.phone_number2 = data['phone2']
                my_motor.email = data['email']
                my_motor.description = data['description']
                my_motor.category = category

                my_motor.save()

                messages.success(request, 'Oferta de Motorizado editada')
                return redirect(reverse('core:inicio'))

            else:

                print("Formulario no valido")
                print(form.errors)
                return redirect(reverse('core:inicio'))

        else:

            data = {
                #Motor
                'brand': my_motor.brand,
                'model': my_motor.title,
                'fuel': my_motor.fuel,
                'transmission': my_motor.transmission,
                'year': my_motor.year,
                'color': my_motor.color,
                #Base
                'title': my_motor.title,
                'price': my_motor.price,
                'location': my_motor.location,
                'phone1': my_motor.phone_number1,
                'phone2': my_motor. phone_number2,
                'email': my_motor.email,
                'description': my_motor.description,
            }

            form = MotorForm(initial=data)

            return render(request, 'motor_app/edit.html',
                          {'form': form,
                           'my_motor': my_motor,
                           'categories': MotorCategory.objects.all()}
                          )

    else:
        messages.error(request, '¡Usuario no autenticado!')
        return redirect(reverse('core:inicio'))


def delete_motor_app(request, id):

    print(f'Motor con id: "{id}" eliminado')

    to_delete = Motor.objects.get(id=id)
    to_delete.delete()

    messages.warning(
                request, 'Oferta de Motor eliminado!'
            )

    return redirect(reverse('core:inicio'))

apps/motor_app/templates/motor_app/edit.html
{% extends 'base.html' %}

{% block title %} Editar Oferta Motorizado {% endblock %}

{% block content %}
<div class="container mt-5 col-9">
    <div class="row">
        <div class="card p-3">
            <h1>Editar Motorizado</h1>
            <form action="#" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-4">
                        <div class="mb-3">
                            {{ form.title.label_tag }}
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            {{ form.price.label_tag }}
                            {{ form.price }}
                            {% if form.price.errors %}
                            <div class="text-danger">
                                {{ form.price.errors }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            {{ form.location.label_tag }}
                            {{ form.location }}
                        </div>
                        <div class="mb-3">
                            {{ form.brand.label_tag }}
                            {{ form.brand }}
                        </div>
                        <div class="mb-3">
                            {{ form.model.label_tag }}
                            {{ form.model }}
                        </div>
                        <div class="mb-3">
                            {{ form.fuel.label_tag }}
                            {{ form.fuel }}
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="mb-3">
                            {{ form.transmission.label_tag }}
                            {{ form.transmission }}
                        </div>
                        <div class="mb-3">
                            {{ form.year.label_tag }}
                            {{ form.year }}
                        </div>
                        <div class="mb-3">
                            {{ form.color.label_tag }}
                            {{ form.color }}
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Categoria:</label>
                            <select class="form-select" id="category_id" name="category_id">
                                <option selected>Seleccionar Categoria</option>
                                {% for category in categories %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="images" class="form-label">Imagenes:</label>
                            <input type="file" multiple class="form-control" id="images" name="images" >
                        </div>
                        <div class="mb-3">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-4   ">
                        <div class="mb-3">
                            {{ form.phone1.label_tag }}
                            {{ form.phone1 }}
                        </div>
                        <div class="mb-3">
                            {{ form.phone2.label_tag }}
                            {{ form.phone2 }}
                        </div>
                        <div class="mb-3">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-warning">Editar Oferta</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/motor_app/templates/motor_app/form.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
<div class="container mt-5 col-6">
    <div class="row">
        <div class="card p-3">
            <h1>Ofertar Motorizado</h1>
            <form action="#" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <div class="mb-3">
                            {{ form.brand.label_tag }}
                            {{ form.brand }}
                        </div>
                        <div class="mb-3">
                            {{ form.model.label_tag }}
                            {{ form.model }}
                        </div>
                        <div class="mb-3">
                            {{ form.fuel.label_tag }}
                            {{ form.fuel }}
                        </div>
                        <div class="mb-3">
                            {{ form.transmission.label_tag }}
                            {{ form.transmission }}
                        </div>
                        <div class="mb-3">
                            <label for="images" class="form-label">Imagenes:</label>
                            <input type="file" multiple  class="form-control" id="images" name="images" required>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                            {{ form.year.label_tag }}
                            {{ form.year }}
                        </div>
                        <div class="mb-3">
                            {{ form.color.label_tag }}
                            {{ form.color }}
                        </div>
                        <div class="mb-3">
                            {{ form.location.label_tag }}
                            {{ form.location }}
                        </div>
                        <div class="mb-3">
                            {{ form.price.label_tag }}
                            {{ form.price }} Gs.
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Categoria:</label>
                            <select class="form-select" id="category_id" name="category_id">
                                <option selected>Seleccionar Categoria</option>
                                {% for category in categories %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Ofertar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/motor_app/templates/motor_app/list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Lista Motorizados {% endblock %}

{% block content %}
{% if entity %}
{% for motor in entity %}
<div class="row m-2 justify-content-center">
    <div class="col-10 card shadow-sm">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-2">
                    {% if motor.images.all %}
                        <img src="{{ motor.images.all.first.image.url }}" alt="{{ motor.title }}" class="img-fluid float-start">
                    {% endif %}
                </div>
                <div class="card-title col-6 mx-3">
                    <a href="{% url 'core:show_detail' id=motor.id %}"
                    class="fw-bolder link-underline link-underline-opacity-0">{{motor.title}}</a>
                    <h5>{{motor.price|intcomma}}</h5>
                    <footer>
                        Ofrecido por <span>{{motor.user}}</span>
                        | Ubicación {{motor.location}}
                    </footer>
                </div>
                <div class="col-3 d-flex justify-content-end align-items-center">
                    {% if user == motor.user %}
                    <a href="{% url 'motor_app:edit_motor_app' id=motor.id %}" class="btn btn-warning me-1 btn-sm">
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger btn-sm me-1" data-bs-toggle="modal"
                        data-bs-target="#delete{{motor.id}}">
                        <i class="bi bi-trash-fill"></i>
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="delete{{motor.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">ELIMINAR OFERTA</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    ¿Seguro que quieres elimar la oferta: {{motor.title}}?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">Close</button>
                                    <a href="{% url 'motor_app:delete_motor_app' id=motor.id %}"
                                        class="btn btn-danger">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endfor %}
<div>
{% include 'includes/paginator.html' %}
    </div>
{% else %}
<div class="row mt-5 justify-content-center">
    <div class="col card shadow-sm text-center">
        <h5 class="m-2">Ofertas no encontradas</h5>
    </div>
</div>
{% endif %}
{% endblock %}

apps/motor_app/templates/motor_app/motor_form.html
{% extends 'base.html' %}

{% block title %} Ofertar Motorizado {% endblock %}

{% block content %}
<div class="container mt-5 col-9">
    <div class="row">
        <div class="card p-3">  
            <h1>Motorizado</h1>
            <form action="{% url 'motor_app:motor_add' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-4">
                        <div class="mb-3">
                            {{ form.title.label_tag }}
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            {{ form.price.label_tag }}
                            {{ form.price }}
                            {% if form.price.errors %}
                            <div class="text-danger">
                                {{ form.price.errors }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            {{ form.location.label_tag }}
                            {{ form.location }}
                        </div>
                        <div class="mb-3">
                            {{ form.brand.label_tag }}
                            {{ form.brand }}
                        </div>
                        <div class="mb-3">
                            {{ form.model.label_tag }}
                            {{ form.model }}
                        </div>
                        <div class="mb-3">
                            {{ form.fuel.label_tag }}
                            {{ form.fuel }}
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="mb-3">
                            {{ form.transmission.label_tag }}
                            {{ form.transmission }}
                        </div>
                        <div class="mb-3">
                            {{ form.year.label_tag }}
                            {{ form.year }}
                        </div>
                        <div class="mb-3">
                            {{ form.color.label_tag }}
                            {{ form.color }}
                        </div>
                        <div class="mb-3">
                            <label for="category_id" class="form-label">Categoria:</label>
                            <select class="form-select" id="category_id" name="category_id">
                                <option selected>Seleccionar Categoria</option>
                                {% for category in categories %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            {{ form.images.label_tag }}
                            {{ form.images }}
                        </div>
                        <div id="additional_image_fields">
                            <!-- Input adicional -->
                        </div>
                        <br>
                        <button type="button" id="add_image_field" class="btn btn-secondary">Agregar más imágenes</button>
                        <br>
                        <br>
                        <div class="mb-3">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-4   ">
                        <div class="mb-3">
                            {{ form.phone1.label_tag }}
                            {{ form.phone1 }}
                        </div>
                        <div class="mb-3">
                            {{ form.phone2.label_tag }}
                            {{ form.phone2 }}
                        </div>
                        <div class="mb-3">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Ofertar</button>
            </form>
        </div>
    </div>
</div>

<script>
    document.getElementById("add_image_field").addEventListener("click", function () {
        var newInput = document.createElement("input");
        newInput.type = "file";
        newInput.name = "images";
        newInput.className = "form-control";
        newInput.multiple = true;
        document.getElementById("additional_image_fields").appendChild(newInput);
    });
</script>
{% endblock %}