apps/core/urls.py
from apps.core.views import index, search_results, favorite_control, show_detail
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='inicio'),
    path('search/', search_results, name='search_results'),
    path('favorito/<int:id>', favorite_control, name='favorite_control'),
    path('detalle/<int:id>', show_detail, name='show_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/electronics/urls.py
""" Electronics routes. """
from apps.electronics.views import electronic_add, electronics_list, edit_electronic, delete_electronic
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'electronics'

urlpatterns = [
    path('agregar/', electronic_add, name='electronic_add'),
    path('lista/<int:id>/', electronics_list, name='electronics_list'),
    path('editar/<int:id>/', edit_electronic, name='edit_electronic'),
    path('eliminar/<int:id>/', delete_electronic, name='delete_electronic'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/furnitures/urls.py
""" Entertainments routes. """
from apps.furnitures.views import furniture_add, furnitures_list, edit_furniture, delete_furniture
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'furnitures'

urlpatterns = [
    path('agregar/', furniture_add, name='furniture_add'),
    path('lista/<int:id>/', furnitures_list, name='furnitures_list'),
    path('editar/<int:id>/', edit_furniture, name='edit_furniture'),
    path('eliminar/<int:id>/', delete_furniture, name='delete_furniture'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/motor_app/urls.py
""" Motors routes. """
from apps.motor_app.views import motor_add, motor_app_list, edit_motor_app, delete_motor_app
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'motor_app'

urlpatterns = [
    path('agregar/', motor_add, name='motor_add'),
    path('lista/<int:id>/', motor_app_list, name='motor_app_list'),
    path('editar/<int:id>/', edit_motor_app, name='edit_motor_app'),
    path('eliminar/<int:id>/', delete_motor_app, name='delete_motor_app'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/users/urls.py
""" Views Users. """
from apps.users.views import login_user, logout_user, register_user, user_profile
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('login_user', login_user, name='login'),
    path('logout_user', logout_user, name='logout'),
    path('register_user', register_user, name='register'),
    path('cuenta/<int:pk>', user_profile, name='user_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("users/", include ("django.contrib.auth.urls")),
    path("users/", include("apps.users.urls")),
    path("motores/", include("apps.motor_app.urls")),
    path("electronica/", include("apps.electronics.urls")),
    path("mobiliarios/", include("apps.furnitures.urls")),
    path("entretenimiento/", include("apps.entertainments.urls")),
]

# Configuración para que se muestren las imagenes en el navegador
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class BaseClass(models.Model):

    user = models.ForeignKey(User, related_name='publication', on_delete=models.CASCADE)
    title = models.CharField(max_length=245, null=False)
    description = models.CharField(max_length=255)
    price = models.CharField(max_length=255, null=False)
    location = models.CharField(max_length=255, null=False)
    # images
    phone_number1 = models.CharField(max_length=100)
    phone_number2 = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True)
    #FAVORITES = MANY TO MANY WITH USERS
    created_at = models.DateTimeField(auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)


class ImageBase(models.Model):
    """Modelo para las imagenes de los productos."""

    image = models.ImageField(upload_to='publication_images/')
    product = models.ForeignKey(to=BaseClass, on_delete=models.CASCADE, related_name='images')

apps/core/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from apps.core.models import BaseClass
from apps.motor_app.models import Motor
from apps.electronics.models import ElectronicCategory
from apps.entertainments.models import EntertainmentCategory
from apps.furnitures.models import FurnitureCategory
from apps.motor_app.models import MotorCategory
from apps.users.models import Profile


# Create your views here.
def index(request):
    """Vista para inicio"""

    context = {
        'electronics': ElectronicCategory.objects.all(),
        'entertainments': EntertainmentCategory.objects.all(),
        'furnitures': FurnitureCategory.objects.all(),
        'motors': MotorCategory.objects.all()
    }

    return render(request, 'nemu/index.html', context)


def search_results(request):
    """Vista para resultados del search. """
    if request.method == 'POST':

        searched = request.POST['search']
        found = BaseClass.objects.filter(title__contains=searched)

        context = {
            'searched': searched,
            'found': found
        }

        return render(request, 'nemu/search_results.html', context)

    else:

        # FALTA AGREGAR PROTECCIÓN REENVIO DE FORMULARIO

        return render(request, 'nemu/search_results.html')


def favorite_control(request, id):

    if request.user.is_authenticated:

        my_user = request.user

        user = Profile.objects.get(id=my_user.id)

        for fav in user.favorites.all():
            print(fav.title)

        publication = BaseClass.objects.get(id=id)

        if not user.favorites.filter(id=publication.id).exists():
            user.favorites.add(publication)
            messages.success(
                request, f'Agregado a favoritos {publication.title}')
        else:
            user.favorites.remove(publication)
            messages.warning(
                request, f'Removido de favoritos {publication.title}')

        return redirect(reverse('core:show_detail', args=[id]))

    else:
        messages.error(request, '¡Usuario no autenticado!')
        return redirect(reverse('core:inicio'))


def show_detail(request, id):

    user = request.user
    publication = BaseClass.objects.get(id=id)

    if Motor.objects.filter(id=publication.id).exists():

        motor_instance = Motor.objects.get(id=id)
        
        fav = False

        if motor_instance.favorites.filter(id=user.id).exists():
            fav = True

        context = {
            'publication': motor_instance,
            'fav': fav
        }

        print('Es una instancia de motor')
        return render(request, 'nemu/motor_show_detail.html', context)

    else:

        fav = False

        if publication.favorites.filter(id=user.id).exists():
            fav = True

        context = {
            'publication': publication,
            'fav': fav
        }

        # TODO: eliminar
        print(f'publication: {publication.__dict__}')
        print(f'Product images: {publication.images.all()}')

        return render(request, 'nemu/show_detail.html', context)

apps/core/templates/nemu/index.html
{% extends 'base.html' %}

{% block title %} Ñemu Market {% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row p-2 justify-content-center">
        <div class="col-4 card m-1 shadow-sm p-2 bg-light">
            <div class="card-body">
                <h5 class="card-title">
                    Electrónica
                    <i class="bi bi-tv"></i>    
                    <ul class="mt-2">
                        {% for category in electronics %}
                        <li><a class="fw-normal fs-6"
                                href="{% url 'electronics:electronics_list' id=category.id %}">{{category.name}}
                            </a></li>
                        {% endfor %}
                    </ul>
                </h5>
            </div>
        </div>
        <div class="col-4 card m-1 shadow-sm p-2 bg-light">
            <div class="card-body">
                <h5 class="card-title">
                    Entretenimiento
                    <i class="bi bi-balloon"></i>
                    <ul class="mt-2">
                        {% for category in entertainments %}
                        <li><a class="fw-normal fs-6" href="{% url 'entertainments:entertainments_list' id=category.id %}">{{category.name}}</a></li>
                        {% endfor %}
                    </ul>
                </h5>
            </div>
        </div>
    </div>
    <div class="row p-2 justify-content-center">
        <div class="col-4 card m-1 shadow-sm p-2 bg-light">
            <div class="card-body">
                <h5 class="card-title">
                    Mobiliario
                    <i class="bi bi-house"></i>
                    <ul class="mt-2">
                        {% for category in furnitures %}
                        <li><a class="fw-normal fs-6" href="{% url 'furnitures:furnitures_list' id=category.id %}">{{category.name}}</a></li>
                        {% endfor %}
                    </ul>
                </h5>
            </div>
        </div>
        <div class="col-4 card m-1 shadow-sm p-2 bg-light">
            <div class="card-body">
                <h5 class="card-title">
                    Motor
                    <i class="bi bi-car-front-fill"></i>
                    <ul class="mt-2">
                        {% for category in motors %}
                        <li><a class="fw-normal fs-6" href="{% url 'motor_app:motor_app_list' id=category.id %}">{{category.name}}</a></li>
                        {% endfor %}
                    </ul>
                </h5>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row mt-4 justify-content-center">
        <div class="col-12">
            <div class="col-12">
                <h3>¿Quienes somos?</h3>
                <p>¡Bienvenido a Ñemu Market! Somos una plataforma de reventa en línea que te permite comprar y vender
                    artículos de segunda mano de manera fácil y segura.</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

apps/core/templates/nemu/motor_show_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Detalles de publicación {% endblock %}

{% block content %}
<div class="row m-2 justify-content-center">
    <div class="col-10 card shadow-sm">
        <div class="card-body">
            <div class="row g-0 mb-2">
                <div class="col-11">
                    <h3>{{publication.title}}</h3>
                </div>
                <div class="col-1">
                    {% if user.is_authenticated %}
                        {% if fav %}
                        <a href="{% url 'core:favorite_control' id=publication.id%}" class="btn btn-secondary btn-sm">
                            <i class="bi bi-star-fill"></i>
                        </a>
                        {% else %}
                        <a href="{% url 'core:favorite_control' id=publication.id%}" class="btn btn-success btn-sm">
                            <i class="bi bi-star-fill"></i>
                        </a>
                        {% endif %}
                    {% else %}
                    <a href="{% url 'users:login'%}" class="btn btn-success btn-sm">
                        <i class="bi bi-star-fill"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="row g-0">
                <div class="col">
                    <p><span class="fw-bolder">Usuario:</span> {{publication.user}}</p>
                </div>
                <div class="col">
                    <p class="h-25 m-1"><span class="fw-bolder">Contacto:</span> {{publication.phone_number1}}</p>
                    {% if publication.phone_number2 %}
                    <p class="h-25 m-1"><span class="fw-bolder">Contacto 2:</span> {{publication.phone_number2}}</p>
                    {% endif %}
                    <p class="h-25 m-1"><span class="fw-bolder">Email:</span> {{publication.email}}</p>
                </div>
                <div class="col text-center">
                    <h2>GS {{publication.price|intcomma}}</h2>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col">
                    <p class="m-0"><span class="fw-bolder">Ubicación:</span> {{publication.location}}</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div id="miCarrusel" class="carousel slide" data-bs-ride="carousel">
                    <!-- Indicadores -->
                    <!-- Imágenes del carrusel -->
                    <div class="carousel-inner">
                        {% for image in publication.images.all %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <div class="d-flex justify-content-center">
                                <img src="{{ image.image.url }}" alt="{{ publication.title }} Image" style="max-width: 100%;" class="mx-auto">
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Controles del carrusel -->
                    <a class="carousel-control-prev" href="#miCarrusel" data-bs-slide="prev" id="custom-prev">
                        <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#miCarrusel" data-bs-slide="next" id="custom-next">
                        <span class="carousel-control-next-icon"></span>
                    </a>
                </div>
            </div>
            <hr>
            <div class="row g-0">
                <div class="col">
                    <p class="h-25 m-1"><span class="fw-bolder">Marca:</span> {{publication.brand}}</p>
                    <p class="h-25 m-1"><span class="fw-bolder">Modelo:</span> {{publication.model}}</p>
                </div>
                <div class="col">
                    <p class="h-25 m-1"><span class="fw-bolder">Año:</span> {{publication.year}}</p>
                    <p class="h-25 m-1"><span class="fw-bolder">Transmisión:</span> {{publication.transmission}}</p>
                </div>
                <div class="col">
                    <p class="h-25 m-1"><span class="fw-bolder">Combustible:</span> {{publication.fuel}}</p>
                    <p class="h-25 m-1"><span class="fw-bolder">Color:</span> {{publication.color}}</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <p class="h-25 m-0"><span class="fw-bolder">Publicado el:</span> {{publication.created_at}}</p>
            </div>
            <div class="row">
                <p class="fw-bolder mt-2 mb-0">Descripción:</p>
                <p>{{publication.description}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/core/templates/nemu/search_results.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Ñemu Market {% endblock %}

{% block content %}

{% if searched %}
<h3 class="mt-4">Buscaste: {{searched}}</h3>

{% if found %}
{% for offer in found %}
<div class="row mt-4 justify-content-center">
    <div class="col-10 card shadow-sm">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-2">
                    {% if offer.images.all %}
                        <img src="{{ offer.images.all.first.image.url }}" alt="{{ offer.title }}" class="img-fluid float-start">
                    {% endif %}
                </div>
                <div class="card-title col-9 mx-3">
                    <a href="{% url 'core:show_detail' id=offer.id %}"
                    class="fw-bolder link-underline link-underline-opacity-0">{{offer.title}}</a>
                    <h5>{{offer.price|intcomma}}</h5>
                    <footer>
                        Ofrecido por <span>{{offer.user}}</span>
                        | Ubicación {{offer.location}}
                    </footer>
                </div>
                <div class="col-1">
                    
                </div>
            </div>
        </div>

    </div>
</div>
{% endfor %}
{% else %}
<div class="row mt-5 justify-content-center">
    <div class="col-10 card shadow-sm text-center">
        <h5 class="mt-2">No se encontraron coincidencias ...</h5>
    </div>
</div>
{% endif %}

{% else %}
<h3 class="mt-4">Olvidaste de ingresar una busqueda :(</h3>

<div class="row mt-5 justify-content-center">
    <div class="col-10 card shadow-sm text-center">
        <h5 class="mt-2">No se encontraron coincidencias ...</h5>
    </div>
</div>
{% endif %}


{% endblock %}

apps/core/templates/nemu/show_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Detalles de publicación {% endblock %}

{% block content %}
<div class="row m-2 justify-content-center">
    <div class="col-10 card shadow-sm">
        <div class="card-body">
            <div class="row g-0 mb-2">
                <div class="col-11">
                    <h3>{{publication.title}}</h3>
                </div>
                <div class="col-1">
                    {% if user.is_authenticated %}
                    {% if fav %}
                    <a href="{% url 'core:favorite_control' id=publication.id%}" class="btn btn-secondary btn-sm">
                        <i class="bi bi-star-fill"></i>
                    </a>
                    {% else %}
                    <a href="{% url 'core:favorite_control' id=publication.id%}" class="btn btn-success btn-sm">
                        <i class="bi bi-star-fill"></i>
                    </a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'users:login'%}" class="btn btn-success btn-sm">
                        <i class="bi bi-star-fill"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="row g-0">
                <div class="col">
                    <p><span class="fw-bolder">Usuario:</span> {{publication.user}}</p>
                </div>
                <div class="col">
                    <p class="h-25 m-1"><span class="fw-bolder">Contacto:</span> {{publication.phone_number1}}</p>
                    {% if publication.phone_number2 %}
                    <p class="h-25 m-1"><span class="fw-bolder">Contacto 2:</span> {{publication.phone_number2}}</p>
                    {% endif %}
                    <p class="h-25 m-1"><span class="fw-bolder">Email:</span> {{publication.email}}</p>
                </div>
                <div class="col text-center">
                    <h2>GS {{publication.price|intcomma}}</h2>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col">
                    <p class="m-0"><span class="fw-bolder">Ubicación:</span> {{publication.location}}</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div id="miCarrusel" class="carousel slide" data-bs-ride="carousel">
                    <!-- Indicadores -->
                    <!-- Imágenes del carrusel -->
                    <div class="carousel-inner">
                        {% for image in publication.images.all %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <div class="d-flex justify-content-center">
                                <img src="{{ image.image.url }}" alt="{{ publication.title }} Image"
                                    style="max-width: 100%;" class="mx-auto">
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Controles del carrusel -->
                    <a class="carousel-control-prev" href="#miCarrusel" data-bs-slide="prev" id="custom-prev">
                        <span class="carousel-control-prev-icon"></span>
                    </a>
                    <a class="carousel-control-next" href="#miCarrusel" data-bs-slide="next" id="custom-next">
                        <span class="carousel-control-next-icon"></span>
                    </a>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <p class="h-25 m-0"><span class="fw-bolder">Publicado el:</span> {{publication.created_at}}</p>
        </div>
        <div class="row">
            <p class="fw-bolder mt-2 mb-0">Descripción:</p>
            <p>{{publication.description}}</p>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#miCarrusel").carousel();
    });
</script>
{% endblock %}