apps/core/urls.py
from apps.core.views import index, search_results, favorite_control, show_detail
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='inicio'),
    path('search/', search_results, name='search_results'),
    path('favorito/<int:id>', favorite_control, name='favorite_control'),
    path('detalle/<int:id>', show_detail, name='show_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/electronics/urls.py
""" Electronics routes. """
from apps.electronics.views import electronic_add, electronics_list, edit_electronic, delete_electronic
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'electronics'

urlpatterns = [
    path('agregar/', electronic_add, name='electronic_add'),
    path('lista/<int:id>/', electronics_list, name='electronics_list'),
    path('editar/<int:id>/', edit_electronic, name='edit_electronic'),
    path('eliminar/<int:id>/', delete_electronic, name='delete_electronic'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/furnitures/urls.py
""" Entertainments routes. """
from apps.furnitures.views import furniture_add, furnitures_list, edit_furniture, delete_furniture
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'furnitures'

urlpatterns = [
    path('agregar/', furniture_add, name='furniture_add'),
    path('lista/<int:id>/', furnitures_list, name='furnitures_list'),
    path('editar/<int:id>/', edit_furniture, name='edit_furniture'),
    path('eliminar/<int:id>/', delete_furniture, name='delete_furniture'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/motor_app/urls.py
""" Motors routes. """
from apps.motor_app.views import motor_add, motor_app_list, edit_motor_app, delete_motor_app
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = 'motor_app'

urlpatterns = [
    path('agregar/', motor_add, name='motor_add'),
    path('lista/<int:id>/', motor_app_list, name='motor_app_list'),
    path('editar/<int:id>/', edit_motor_app, name='edit_motor_app'),
    path('eliminar/<int:id>/', delete_motor_app, name='delete_motor_app'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/users/urls.py
""" Views Users. """
from apps.users.views import login_user, logout_user, register_user, user_profile
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import messages
from django.urls import path

app_name = 'users'

urlpatterns = [
    path('login_user', login_user, name='login'),
    path('logout_user', logout_user, name='logout'),
    path('register_user', register_user, name='register'),
    path('cuenta/<int:pk>', user_profile, name='user_profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("users/", include ("django.contrib.auth.urls")),
    path("users/", include("apps.users.urls")),
    path("motores/", include("apps.motor_app.urls")),
    path("electronica/", include("apps.electronics.urls")),
    path("mobiliarios/", include("apps.furnitures.urls")),
    path("entretenimiento/", include("apps.entertainments.urls")),
]

# Configuración para que se muestren las imagenes en el navegador
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class BaseClass(models.Model):

    user = models.ForeignKey(User, related_name='publication', on_delete=models.CASCADE)
    title = models.CharField(max_length=245, null=False)
    description = models.CharField(max_length=255)
    price = models.CharField(max_length=255, null=False)
    location = models.CharField(max_length=255, null=False)
    # images
    phone_number1 = models.CharField(max_length=100)
    phone_number2 = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True)
    #FAVORITES = MANY TO MANY WITH USERS
    created_at = models.DateTimeField(auto_now_add=True, null=False)
    updated_at = models.DateTimeField(auto_now=True, null=False)


class ImageBase(models.Model):
    """Modelo para las imagenes de los productos."""

    image = models.ImageField(upload_to='publication_images/')
    product = models.ForeignKey(to=BaseClass, on_delete=models.CASCADE, related_name='images')

apps/core/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from apps.core.models import BaseClass
from apps.motor_app.models import Motor
from apps.electronics.models import ElectronicCategory
from apps.entertainments.models import EntertainmentCategory
from apps.furnitures.models import FurnitureCategory
from apps.motor_app.models import MotorCategory
from apps.users.models import Profile


# Create your views here.
def index(request):
    """Vista para inicio"""

    context = {
        'electronics': ElectronicCategory.objects.all(),
        'entertainments': EntertainmentCategory.objects.all(),
        'furnitures': FurnitureCategory.objects.all(),
        'motors': MotorCategory.objects.all()
    }

    return render(request, 'nemu/index.html', context)


def search_results(request):
    """Vista para resultados del search. """
    if request.method == 'POST':

        searched = request.POST['search']
        found = BaseClass.objects.filter(title__contains=searched)

        context = {
            'searched': searched,
            'found': found
        }

        return render(request, 'nemu/search_results.html', context)

    else:

        # FALTA AGREGAR PROTECCIÓN REENVIO DE FORMULARIO

        return render(request, 'nemu/search_results.html')


def favorite_control(request, id):

    if request.user.is_authenticated:

        my_user = request.user

        user = Profile.objects.get(id=my_user.id)

        for fav in user.favorites.all():
            print(fav.title)

        publication = BaseClass.objects.get(id=id)

        if not user.favorites.filter(id=publication.id).exists():
            user.favorites.add(publication)
            messages.success(
                request, f'Agregado a favoritos {publication.title}')
        else:
            user.favorites.remove(publication)
            messages.warning(
                request, f'Removido de favoritos {publication.title}')

        return redirect(reverse('core:show_detail', args=[id]))

    else:
        messages.error(request, '¡Usuario no autenticado!')
        return redirect(reverse('core:inicio'))


def show_detail(request, id):

    user = request.user
    publication = BaseClass.objects.get(id=id)

    if Motor.objects.filter(id=publication.id).exists():

        motor_instance = Motor.objects.get(id=id)
        
        fav = False

        if motor_instance.favorites.filter(id=user.id).exists():
            fav = True

        context = {
            'publication': motor_instance,
            'fav': fav
        }

        print('Es una instancia de motor')
        return render(request, 'nemu/motor_show_detail.html', context)

    else:

        fav = False

        if publication.favorites.filter(id=user.id).exists():
            fav = True

        context = {
            'publication': publication,
            'fav': fav
        }

        # TODO: eliminar
        print(f'publication: {publication.__dict__}')
        print(f'Product images: {publication.images.all()}')

        return render(request, 'nemu/show_detail.html', context)

apps/core/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
  <div class="container-fluid mx-5">
    <!-- Nombre de la página en el centro -->
    <a class="navbar-brand" href="{% url 'core:inicio' %}">
      <img src="{% static 'images/ñemu_market.png' %}" alt="Logo" width="50" height="44"
        class="d-inline-block align-text-center"> 
        Ñemu Market
    </a>

    <!-- Buscador en el medio -->
    <form action="{% url 'core:search_results' %}" method="post" class="d-flex" role="search">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="¿Qué estas buscando ... ?" aria-label="Search"
        name="search">
      <button class="btn btn-outline-success" type="submit">Buscar</button>
      {% if user.is_authenticated %}
      <div class="ms-1 dropdown">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          Ofertar
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'electronics:electronic_add' %}">Electrónica</a></li>
          <li><a class="dropdown-item" href="{% url 'entertainments:entertainment_add' %}">Entretenimiento</a></li>
          <li><a class="dropdown-item" href="{% url 'furnitures:furniture_add' %}">Mobiliario</a></li>
          <li><a class="dropdown-item" href="{% url 'motor_app:motor_add' %}">Motor</a></li>
        </ul>
      </div>
      {% endif %}
    </form>

    <!-- Enlaces de Registro e Inicio de Sesión a la derecha -->
    <div class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'users:user_profile' request.user.id %}">
          <i class="bi bi-person-fill"></i>
          Mi Cuenta
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'users:logout' %}">
          <i class="bi bi-box-arrow-in-left"></i>
          Cerrar sesión
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'users:register' %}">
          <i class="bi bi-person-add"></i>
          Registrarse
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'users:login' %}">
          <i class="bi bi-box-arrow-in-right"></i>
          Iniciar sesión
        </a>
      </li>
      {% endif %}
    </div>
  </div>

</nav>

apps/core/templates/includes/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}